# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.migrations import RunPython


def create_initial_values(apps, schema_editor):
    Importance = apps.get_model('bdaygui', 'Importance')
    db_alias = schema_editor.connection.alias
    Importance.objects.using(db_alias).bulk_create([
        Importance(code=1, name=u'Нужно поздравлять'),
        Importance(code=2, name=u'Не нужно поздравлять'),
        Importance(code=3, name=u'Проверить ещё раз'),
    ])


def remove_initial_values(apps, schema_editor):
    Importance = apps.get_model('bdaygui', 'Importance')
    db_alias = schema_editor.connection.alias
    Importance.objects.using(db_alias).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bdaygui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='\u041a\u043e\u0434')),
                ('name', models.CharField(max_length=16, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'importance',
                'verbose_name': '\u0421\u0442\u0435\u043f\u0435\u043d\u044c \u0432\u0430\u0436\u043d\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u0421\u0442\u0435\u043f\u0435\u043d\u0438 \u0432\u0430\u0436\u043d\u043e\u0441\u0442\u0438',
            },
        ),
        RunPython(create_initial_values, remove_initial_values),
    ]
