# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdaygui', '0003_use_importance_from_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='important',
        ),
    ]
